github:
  bucket:
    # 配置仓库所属的用户名（如果是自己创建的，就是自己的用户名）
    user: "Marthew01"
    # 配置仓库名称
    repository: "twitter-bucket"
    # 配置自己的acccessToken
    access-token: "c0921714af7dfdb8603bf93ead12a3a5614e5da1"
    url: "https://cdn.jsdelivr.net/gh/${github.bucket.user}/${github.bucket.repository}/"
    api: "https://api.github.com/repos/${github.bucket.user}/${github.bucket.repository}/contents/"

server:
  port: 9090
